---
name: Release

on:
  push:
    branches: [ main ]
    tags:
      - v*

jobs:
  release:
    name: Released on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Caching
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: ${{matrix.os}}-bazel
      - name: Install
        run: make install
      - name: Build
        run: make build
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: bazel-buildfarm-artifact
          path: |
            bazel-bin/src/main/java/build/buildfarm/*_deploy.jar
            bazel-bin/src/main/java/build/buildfarm/tools/*_deploy.jar
  push:
    name: Pushed on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: bazel-buildfarm-artifact
      - name: Push
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "angersax@sina.com"
          echo $PWD
          ls -a
